package com.seb.springboot.productservice.repositories;

import com.seb.springboot.productservice.models.Category;
import com.seb.springboot.productservice.models.Product;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;
import java.util.Optional;

public interface ProductRepository extends JpaRepository<Product, Long> {

    Product save(Product product);
    // the attributes that are automatically generated by DB will not be in the param, but will be there in
    // returned object. E.g. Primary Key

    List<Product> findAll();

    Product findByIdEquals(Long productId);

    Product deleteProductById(Long productId);

    Product findByTitle(String title);

    List<Product> findAllByCategory_Title(String category);

}
